spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/silkpay
    driver-class-name: org.postgresql.Driver
    username: Saltanat
    password: 1705
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL10Dialect